name: buf-pull-request
on: pull_request
jobs:
  build-and-lint-execution-apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.15.1"
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "execution-apis/proto"
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "execution-apis/proto"
          # The 'main' branch of the GitHub repository that defines the module.
          against: "https://github.com/astriaorg/astria-rpc.git#branch=main,ref=HEAD~1,subdir=execution-apis/proto"
